import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fef7ff",
        "on-background": "#1d1a24",
        surface: "#fef7ff",
        "on-surface": "#1d1a24",
        "surface-container-lowest": "#ffffff",
        primary: "#630ed4",
        "on-primary": "#ffffff",
        "primary-container": "#7c3aed",
        secondary: "#655c5d",
        "on-secondary": "#ffffff",
        "secondary-container": "#eddfe0",
        outline: "#7b7487",
        "rose-50": "#fff1f2",
        "rose-100": "#ffe4e6",
        "rose-400": "#fb7185",
        "violet-300": "#c4b5fd",
        "violet-400": "#a78bfa",
        "violet-500": "#8b5cf6",
        "violet-600": "#7c3aed",
        "violet-900": "#4c1d95",
        
        // Admin Dashboard Colors
        "admin-outline-variant": "#404944",
        "admin-secondary-container": "#214f41",
        "admin-on-primary": "#00382a",
        "admin-tertiary-fixed": "#c7eadd",
        "admin-tertiary": "#d3f6e8",
        "admin-on-secondary": "#04382b",
        "admin-on-surface": "#e1e3e0",
        "admin-outline": "#8a938e",
        "admin-primary-fixed": "#b8eed8",
        "admin-on-primary-fixed": "#002117",
        "admin-surface-dim": "#111413",
        "admin-inverse-surface": "#e1e3e0",
        "admin-secondary": "#a1d1bf",
        "admin-on-secondary-fixed": "#002118",
        "admin-surface": "#111413",
        "admin-secondary-fixed": "#bcedda",
        "admin-primary-container": "#a7ddc7",
        "admin-surface-container-lowest": "#0c0f0d",
        "admin-background": "#111413",
        "admin-primary-fixed-dim": "#9cd2bc",
        "admin-tertiary-fixed-dim": "#accec1",
        "admin-surface-container": "#1d201f",
        "admin-secondary-fixed-dim": "#a1d1bf",
        "admin-on-error": "#690005",
        "admin-error-container": "#93000a",
        "admin-error": "#ffb4ab",
        "admin-on-error-container": "#ffdad6",
        "admin-on-secondary-container": "#90bfae",
        "admin-surface-container-highest": "#333534",
        "admin-on-primary-fixed-variant": "#1a4f3f",
        "admin-surface-bright": "#373a38",
        "admin-on-secondary-fixed-variant": "#214f41",
        "admin-inverse-primary": "#356856",
        "admin-on-primary-container": "#306352",
        "admin-surface-tint": "#9cd2bc",
        "admin-surface-container-high": "#282b29",
        "admin-on-tertiary-container": "#416056",
        "admin-surface-container-low": "#191c1b",
        "admin-on-surface-variant": "#c0c9c3",
        "admin-on-tertiary": "#17362d",
        "admin-tertiary-container": "#b7d9cc",
        "admin-on-background": "#e1e3e0",
        "admin-surface-variant": "#333534",
        "admin-on-tertiary-fixed-variant": "#2e4d43",
        "admin-primary": "#c3fae3",
        "admin-on-tertiary-fixed": "#002019",
        "admin-inverse-on-surface": "#2e312f"
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
      spacing: {
        "margin-mobile": "1rem",
        "margin-desktop": "5rem",
        safe: "env(safe-area-inset-bottom)",
        "gutter": "24px",
        "sm": "12px",
        "xl": "64px",
        "xs": "4px",
        "base": "8px",
        "lg": "40px",
        "md": "24px",
      }
    },
  },
  plugins: [],
};
export default config;